[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "3001" 